version: "3.9"

services:
  datasource:
    build:
      context: .
      dockerfile: DB.Dockerfile
    hostname: "${DOCKER_NAME}-datasource"
    container_name: "${DOCKER_NAME}-datasource"
    restart: always
    networks:
      - "cfa"
    environment:
      - "SA_PASSWORD=${DOCKER_SQL_PASSWORD}"
  api:
    depends_on:
      - datasource
    build:
      context: .
      dockerfile: Web.Dockerfile
    hostname: ${DOCKER_NAME}-api
    container_name: ${DOCKER_NAME}-api
    restart: always
    networks:
      - "cfa"
  minio:
    image: quay.io/minio/minio
    hostname: ${DOCKER_NAME}-minio
    container_name:  ${DOCKER_NAME}-minio
    restart: always
    networks:
      - "cfa"
    volumes:
      - /minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=adminpassword!"
    command: server /data --console-address ":9001"

  minioclient:
    image: minio/mc
    container_name: minio_client
    depends_on:
      - minio
    entrypoint: >
      bash -c
           "/usr/bin/mc alias set myminio http://${DOCKER_NAME}-minio admin adminpassword!;
            /usr/bin/mc mb myminio/cfa;
            /usr/bin/mc policy set public myminio/cfa;
            /usr/bin/mc admin user add myminio newuser newuser123;
            /usr/bin/mc admin policy set myminio readwrite user=newuser
            /usr/bin/mc admin group add newgroup newuser;
      exit 0;"
    networks:
      - "cfa"
networks:
  cfa:
    name: cfa
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1
