version: "3.9"

services:
  datasource:
    build:
      context: .
      dockerfile: DB.Dockerfile
    ports:
    - "1433:1433"
    hostname: cfa-datasource
    restart: always
    networks:
      cfa:
        ipv4_address: 172.22.1.3
  api:
    depends_on:
      - datasource
    build:
      context: .
      dockerfile: Web.Dockerfile
    ports:
      - "5000:80"
    hostname: cfa-api
    restart: always
    networks:
      cfa:
        ipv4_address: 172.22.1.2
  front:
    build:
      context: .
      dockerfile: AccountSim.Dockerfile
    ports:
      - "5001:80"
    hostname: account-sim
    networks:
      cfa:
        ipv4_address: 172.22.1.4
  proxy:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    ports:
      - "5002:80"
    networks:
      cfa:
        ipv4_address: 172.22.1.5
networks:
  cfa:
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1
